### ISSUE TITLE
[BUG] 有4-5个卡牌几乎每天重复，即使每次点击”容易“

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#29]
**Describe the bug**
有4-5个卡牌几乎每天重复，即使每次点击”容易“

**To Reproduce**
我不知道这个该怎么重复的？
呈现整个obsidian库？
还是说，我选择将复习日期显示在卡片后，确认一下情况？即下面选项确认为是
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/47209925/ba70afc6-3a55-4d19-9aad-b9ed8692e29b)

**Comment by Newdea** [comment]
插件版本？
卡片内容、行号经常变动么，
对应的 容易 显示的复习间隔是多长时间？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月11日(周一) 中午11:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [open-spaced-repetition/obsidian-spaced-repetition-recall] [BUG] 有4-5个卡牌几乎每天重复，即使每次点击”容易“ (Issue #29)




 
Describe the bug
 有4-5个卡牌几乎每天重复，即使每次点击”容易“
 
To Reproduce
 这个不知道该怎么重复的
  
Go to '...' 

Click on '....' 

Scroll down to '....' 

See error 
 
Expected behavior
 A clear and concise description of what you expected to happen.
 
Screenshots
 If applicable, add screenshots to help explain the bug. This could be the logs in the developer console (CTRL + SHIFT + i).
 
Versions (please complete the following information):
  
OS: [e.g. iOS] 

Obsidian version: [e.g. v0.12.4] 

Plugin version: [e.g. v1.4.9] 

If on desktop, Installer version: [run this.navigator.appVersion on the developer console, e.g. 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.3 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36"] 
 
Additional context
 Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by dryezl** [comment]
复习日期有问题，因为三个不同难度显示的时间是一样的
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/47209925/b1ae24d8-11cf-4f8d-b3d9-3f313507417a)

将这个不停重复的卡片换到同一个笔记的不同位置，仍然是显示继续重复的

其他不停重复的卡片也有类似的情况的

插件版本是[1.10.5.3](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/releases/tag/1.10.5.3)

不停重复的卡片内容不怎么变化的，但是行号会经常变化，因为和其他卡片都在一个note里面。所以如果对其他卡片进行编辑时会有影响。

**Comment by dryezl** [comment]
如果将内容移动到另外的笔记，复习该卡片底下会自动生成下面内容的
```txt
<!--SR:!2023-12-17,6,2!2000-01-01,1,250!2000-01-01,1,250!2000-01-01,1,250!2000-01-01,1,250!2000-01-01,1,250!2000-01-01,1,250!2000-01-01,1,250-->
```

卡片内容是  
```txt
`vim` normal mode ==`gn`== enable character-wise and select ==next== match pattern
`vim` normal mode ==`gN`== enable character-wise and select ==previous== match pattern


`vim` regular pattern ==`<`== means the ==start== of a word
`vim` regular pattern ==`>`== means the ==end== of a word
```

**Comment by Newdea** [comment]
这有点奇怪，
看你的描述，设置 是这样吧：
位置：保存在笔记，
算法： 默认

这样的话，只要卡片后的时间信息在（移动位置或移到不同笔记，也不影响），你点击“容易”后，时间信息会同步更新的，不会每天重复的。
你感觉重复是因这组卡片中的挖空有点多，每天显示的是这组卡片不同的挖空。

---
另外，
1. 截图中显示的时间间隔有点怪，应该是你手动修改过卡片后的时间信息吧，
2. 卡片的信息`<!--SR:!2023-12-17,6,2`， 明显最后一个修改的不合理，这个值最小是130

建议，一组卡片中的挖空不要过多，如果多的话，可以考虑重新拆分卡片。

你再确认下，欢迎反馈。

**Comment by Newdea** [comment]
这有点奇怪，
看你的描述，设置 是这样吧：
位置：保存在笔记，
算法： 默认

这样的话，只要卡片后的时间信息在（移动位置或移到不同笔记，也不影响），你点击“容易”后，时间信息会同步更新的，不会每天重复的。
你感觉重复是因这组卡片中的挖空有点多，每天显示的是这组卡片不同的挖空。

---
另外，
1. 截图中显示的时间间隔有点怪，应该是你手动修改过卡片后的时间信息吧，
2. 卡片的信息`<!--SR:!2023-12-17,6,2`， 明显最后一个修改的不合理，这个值最小是130

建议，一组卡片中的挖空不要过多，如果多的话，可以考虑重新拆分卡片。

你再确认下，欢迎反馈。

**Comment by Newdea** [comment]
那就应该是原插件没有禁用，设置单独保存，是不会在卡片后加信息的

挖空，知乎上有许多文章教程的。

**Comment by dryezl** [comment]
偶尔会有一两个卡片不停重复。卡片均是有两个或以上的挖空的

目前的解决方法是将上述卡片的挖空数量控制到一个

**Comment by Newdea** [comment]
嗯，看个人使用习惯了，这个设置项也会影响
![Screenshot_2023-12-13-09-51-29-446_md obsidian-edit](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/a4a0cdbc-94cd-42f3-91b4-af6a34ff7482)

**Comment by Newdea** [comment]
修改了一版，你试下看解决没，里面加入了些调试信息，如果还这样重复，应该会有提示

**Comment by Newdea** [comment]
这个问题就先关了，后续出现再说
