### ISSUE TITLE
[Bug]: 除点击复习队列的其他方式新打开一篇待复习笔记均不能启动悬浮栏

### ISSUE THREAD

**Issue by tangwells** [open-spaced-repetition/obsidian-spaced-repetition-recall#57]
### Describe the bug

除点击复习队列的其他方式新打开一篇待复习笔记均不能启动悬浮栏。我重启 ob 后以命令栏和右下角的状态栏两次新打开一篇笔记，控制台报错如下：
<img width="735" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/a5bf2926-a43c-4099-8fc3-a3b4d1491d6e">

### To Reproduce

1. 使用命令栏或状态栏新打开一篇笔记。

### Expected behavior

使用命令栏或状态栏新打开一篇笔记应出现悬浮栏。

### OS of your device

mac os sonoma 14.5

### Obsidian version

v1.6.3

### Plugin version

v1.12.4.5

**Comment by tangwells** [comment]
我使用你先前发给我的测试用 main.js，能正常通过命令栏和状态栏打开悬浮栏，就是稍微有点小
<img width="1394" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/3e54264c-e050-4f1b-b419-adf1c34e78ce">

**Comment by Newdea** [comment]
下载zip文件，解压后替换那三个对应文件，改动比较多



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月23日(周日) 上午7:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [open-spaced-repetition/obsidian-spaced-repetition-recall] [Bug]: 除点击复习队列的其他方式新打开一篇待复习笔记均不能启动悬浮栏 (Issue #57)




 
Describe the bug
 
除点击复习队列的其他方式新打开一篇待复习笔记均不能启动悬浮栏。我重启 ob 后以命令栏和右下角的状态栏两次新打开一篇笔记，控制台报错如下：
 image.png (view on web)
 
To Reproduce
  
使用命令栏或状态栏新打开一篇笔记。
  
Expected behavior
 
使用命令栏或状态栏新打开一篇笔记应出现悬浮栏。
 
Screenshots
 
No response
 
OS of your device
 
mac os sonoma 14.5
 
Obsidian version
 
v1.6.3
 
Plugin version
 
v1.12.4.5
 
Installer version
 
No response
 
Additional context
 
No response
 
Config file
 
No response

**Comment by tangwells** [comment]
大佬，我就是因为更新了最新的插件版本而导致出现了我所报告了两个问题。反而是原先你曾给我发的测试版本能正常使用。

**Comment by Newdea** [comment]
这三个文件都更新了么，你看下文件修改时间，我这边是正常的。

![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/2edc1841-c311-4d0b-8121-8a5cf1485d12)
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/3f7cd1c1-204a-45ce-907b-512c1367011c)

![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/09a9ba9e-1622-4e96-bb89-7bb4828791e0)

**Comment by tangwells** [comment]
我无论是通过压缩文件的替换，还是那三个文件的下载直接替换都无法解决这个问题。只要试图通过命令栏或者状态栏打开一篇新笔记，在控制台都会出现这样的报错：
<img width="563" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/d94ccb0f-ac10-4fc6-a2ae-2c41489ea2b3">
是否可能您重新上传一下您的代码呢？

**Comment by tangwells** [comment]
大佬，我发现这个问题以及我反馈了重来不跳转的 bug只出现我的带有#review标签的复习队列，对于另一个复习队列是不存在这两个问题的。

**Comment by tangwells** [comment]
大佬，更新之后问题变得更奇怪了。现在是对于我的带有#review标签的复习队列，无论是开始复习时打开一篇笔记，还是复习完后跳转到下一篇笔记，都会自动弹出 item info 窗口。
而且这个问题在同一个库的另一个队列是不存在的，在新库新建立的复习队列也不存在，仅在这个#review的复习队列里存在。
控制台的截图如下：
<img width="560" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/1a19372f-ab16-47f2-b340-e5f03c663d99">
录制的视频如下：
[IMG_2800.MOV.zip](https://github.com/user-attachments/files/15948918/IMG_2800.MOV.zip)

**Comment by Newdea** [comment]
> 对于我的带有#review标签的复习队列，无论是开始复习时打开一篇笔记，还是复习完后跳转到下一篇笔记，都会自动弹出 item info 窗口。

还是问题 #56 ，已经在那里回复了。


----

这个issue 提的不能启动悬浮栏，还在么？

**Comment by tangwells** [comment]
这个问题已经消失了，虽然我也不知道为啥
